# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 1	Chris Evans		1997	FALSE
# Biodiversity: Wild About Life!	1	1997	FALSE

actor1 = Actor.create(name: "Chris Evans", year_first_film: 1997, academy_award: FALSE)
actor2 = Actor.create(name: "Robert Downey, Jr.", year_first_film: 1970, academy_award: TRUE)
actor3 = Actor.create(name: "Jennifer Lawrence", year_first_film: 2008, academy_award: TRUE)
actor4 = Actor.create(name: "Channing Tatum", year_first_film: 2006, academy_award: FALSE)
actor5 = Actor.create(name: "George Clooney", year_first_film: 1988, academy_award: TRUE)
actor6 = Actor.create(name: "Johnny Depp", year_first_film: 1984, academy_award: TRUE)
actor7 = Actor.create(name: "Margot Robbie", year_first_film: 2011, academy_award: TRUE)
actor8 = Actor.create(name: "Jared Leto", year_first_film: 1995, academy_award: TRUE)
actor9 = Actor.create(name: "Ryan Reynolds", year_first_film: 2002, academy_award: FALSE)
actor10 = Actor.create(name: "Ryan Gosling", year_first_film: 2001, academy_award: TRUE)
actor11 = Actor.create(name: "Scarlett Johansson", year_first_film: 1996, academy_award: TRUE)
actor12 = Actor.create(name: "Brad Pitt", year_first_film: 1988, academy_award: TRUE)
actor13 = Actor.create(name: "Matt Damon", year_first_film: 1988, academy_award: TRUE)
actor14 = Actor.create(name: "Will Smith", year_first_film: 1993, academy_award: TRUE)
actor15 = Actor.create(name: "Paul Rudd", year_first_film: 1995, academy_award: FALSE)

Movie.create(name: "Biodiversity: Wild About Life!", year: 1997, academy_award: false, actor_id: actor1.id)

#artists

artist1 = Artist.create(name: "The Beatles", debut_year: 1960, grammy_winner: TRUE)
artist2 = Artist.create(name: "Metallica", debut_year: 1981, grammy_winner: TRUE)
artist3 = Artist.create(name: "Taylor Swift", debut_year: 2006, grammy_winner: TRUE)
artist4 = Artist.create(name: "NWA", debut_year: 1986, grammy_winner: FALSE)
artist5 = Artist.create(name: "Periphery", debut_year: 2005, grammy_winner: FALSE)
artist6 = Artist.create(name: "Rolling Stones", debut_year: 1962, grammy_winner: TRUE)
artist7 = Artist.create(name: "The Eagles", debut_year: 1971, grammy_winner: TRUE)
artist8 = Artist.create(name: "Eminem", debut_year: 1988, grammy_winner: TRUE)
artist9 = Artist.create(name: "Mariah Carey", debut_year: 1990, grammy_winner: TRUE)
artist10 = Artist.create(name: "Johnny Cash", debut_year: 1957, grammy_winner: TRUE)
artist11 = Artist.create(name: "Oasis", debut_year: 1991, grammy_winner: TRUE)
artist12 = Artist.create(name: "Slipknot", debut_year: 1995, grammy_winner: TRUE)
artist13 = Artist.create(name: "Animals as Leaders", debut_year: 2007, grammy_winner: FALSE)
artist14 = Artist.create(name: "Led Zeppelin", debut_year: 1968, grammy_winner: TRUE)
artist15 = Artist.create(name: "Black Sabbath", debut_year: 1968, grammy_winner: TRUE)

#songs

Song.create(name: "Hey Jude", length: 431, top_100: TRUE, artist_id: artist1.id)
Song.create(name: "Come Together", length: 259, top_100: TRUE, artist_id: artist1.id)
Song.create(name: "Yesterday", length: 123, top_100: TRUE, artist_id: artist1.id)
Song.create(name: "One", length: 447, top_100: FALSE, artist_id: artist2.id)
Song.create(name: "Enter Sandman", length: 332, top_100: TRUE, artist_id: artist2.id)
Song.create(name: "Nothing Else Matters", length: 388, top_100: TRUE, artist_id: artist2.id)
Song.create(name: "Shake it Off", length: 219, top_100: TRUE, artist_id: artist3.id)
Song.create(name: "Love Story", length: 234, top_100: TRUE, artist_id: artist3.id)
Song.create(name: "Bad Blood", length: 224, top_100: TRUE, artist_id: artist3.id)
Song.create(name: "Straight Outta Compton", length: 266, top_100: TRUE, artist_id: artist4.id)
Song.create(name: "Express Yourself", length: 266, top_100: TRUE, artist_id: artist4.id)
Song.create(name: "Marigold", length: 440, top_100: FALSE, artist_id: artist5.id)
Song.create(name: "Jetpacks Was Yes", length: 240, top_100: FALSE, artist_id: artist5.id)
Song.create(name: "Ragnarok", length: 355, top_100: FALSE, artist_id: artist5.id)
Song.create(name: "Sympathy For the Devil", length: 458, top_100: TRUE, artist_id: artist6.id)
Song.create(name: "Painted Black", length: 254, top_100: TRUE, artist_id: artist6.id)
Song.create(name: "Gimme Shelter", length: 310, top_100: TRUE, artist_id: artist6.id)
Song.create(name: "Hotel California", length: 340, top_100: TRUE, artist_id: artist7.id)
Song.create(name: "Life In The Fast Lane", length: 326, top_100: TRUE, artist_id: artist7.id)
Song.create(name: "Desperado", length: 221, top_100: FALSE, artist_id: artist7.id)
Song.create(name: "Without Me", length: 340, top_100: TRUE, artist_id: artist8.id)
Song.create(name: "Rap God", length: 304, top_100: TRUE, artist_id: artist8.id)
Song.create(name: "The Real Slim Shady", length: 240, top_100: TRUE, artist_id: artist8.id)
Song.create(name: "We Belong Together", length: 225, top_100: TRUE, artist_id: artist9.id)
Song.create(name: "Without You", length: 312, top_100: TRUE, artist_id: artist9.id)
Song.create(name: "Hero", length: 231, top_100: FALSE, artist_id: artist9.id)
Song.create(name: "I Walk The Line", length: 145, top_100: TRUE, artist_id: artist10.id)
Song.create(name: "Ring of Fire", length: 226, top_100: TRUE, artist_id: artist10.id)
Song.create(name: "Hurt", length: 238, top_100: TRUE, artist_id: artist10.id)
Song.create(name: "Wonderwall", length: 240, top_100: TRUE, artist_id: artist11.id)
Song.create(name: "Dont Look Back In Anger", length: 226, top_100: TRUE, artist_id: artist11.id)
Song.create(name: "Champagne Supernova", length: 523, top_100: FALSE, artist_id: artist11.id)
Song.create(name: "Wait and Bleed", length: 220, top_100: FALSE, artist_id: artist12.id)
Song.create(name: "Snuff", length: 340, top_100: TRUE, artist_id: artist12.id)
Song.create(name: "Before I Forget", length: 356, top_100: TRUE, artist_id: artist12.id)
Song.create(name: "Physical Education", length: 540, top_100: FALSE, artist_id: artist13.id)
Song.create(name: "Cafo", length: 420, top_100: FALSE, artist_id: artist13.id)
Song.create(name: "Kalimba", length: 355, top_100: FALSE, artist_id: artist13.id)
Song.create(name: "Stairway To Heaven", length: 450, top_100: TRUE, artist_id: artist14.id)
Song.create(name: "Black Dog", length: 240, top_100: TRUE, artist_id: artist14.id)
Song.create(name: "Heartbreaker", length: 317, top_100: TRUE, artist_id: artist14.id)
Song.create(name: "Paranoid", length: 236, top_100: TRUE, artist_id: artist15.id)
Song.create(name: "War Pigs", length: 359, top_100: TRUE, artist_id: artist15.id)
Song.create(name: "Iron Man", length: 217, top_100: TRUE, artist_id: artist15.id)
